import type { Listing } from "@/lib/listings/types"

/** Mirrors supabase/migrations/20260918000000_listings.sql. Hero uses the first three. */
export const seedListings: Listing[] = [
  {
    id: "a1e1c0a0-0b11-4c22-8d33-000000000001",
    name: "St. James Night Shelter",
    kind: "shelter",
    freshness: "live",
    lastConfirmedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    pets: "service_only",
    couples: "same_room",
    parkingStatus: null,
    vehicleNote: null,
    city: "San Jose",
    orgName: "St. James Community",
  },
  {
    id: "a1e1c0a0-0b11-4c22-8d33-000000000005",
    name: "Senter Rd Safe Parking",
    kind: "parking",
    freshness: "live",
    lastConfirmedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    pets: "any",
    couples: null,
    parkingStatus: "open",
    vehicleNote: "Cars and vans under 22 ft",
    city: "San Jose",
    orgName: "City Safe Parking",
  },
  {
    id: "a1e1c0a0-0b11-4c22-8d33-000000000002",
    name: "Guadalupe Family Shelter",
    kind: "shelter",
    freshness: "recent",
    lastConfirmedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    pets: "small_pets",
    couples: "same_room",
    parkingStatus: null,
    vehicleNote: null,
    city: "San Jose",
    orgName: "South Bay Family Housing",
  },
  {
    id: "a1e1c0a0-0b11-4c22-8d33-000000000003",
    name: "Eastside Women's Overnight",
    kind: "shelter",
    freshness: "call_first",
    lastConfirmedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    pets: "not_allowed",
    couples: "not_allowed",
    parkingStatus: null,
    vehicleNote: null,
    city: "San Jose",
    orgName: "Eastside Women's Overnight",
  },
  {
    id: "a1e1c0a0-0b11-4c22-8d33-000000000004",
    name: "County Overflow Gym",
    kind: "shelter",
    freshness: "live",
    lastConfirmedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    pets: "service_only",
    couples: "separate_rooms",
    parkingStatus: null,
    vehicleNote: null,
    city: "Santa Clara",
    orgName: "County Winter Shelter",
  },
  {
    id: "a1e1c0a0-0b11-4c22-8d33-000000000006",
    name: "Westside RV Lot",
    kind: "parking",
    freshness: "recent",
    lastConfirmedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    pets: "any",
    couples: null,
    parkingStatus: "waitlist",
    vehicleNote: "RVs and trailers, max 32 ft",
    city: "San Jose",
    orgName: "Westside Faith Collaborative",
  },
]
